### ISSUE TITLE
Editor Crashes on Sign in with Username and Password Fail

### ISSUE THREAD

**Issue by WeeTomatoBall** [IamKingWaiMark/FBP#1]
Binded an event to the fail of the Sign in with Username and Password. The editor crashes if I add a delay anywhere after it.
![image](https://user-images.githubusercontent.com/82912271/197367706-bbc357d4-b1da-4d0c-9270-062a2fbe30f0.png)
![image](https://user-images.githubusercontent.com/82912271/197367727-b6aa133a-a382-470e-ad60-b92cc912d184.png)
Edit: Same thing happens for success.

**Comment by IamKingWaiMark** [comment]
Hi, did you try binding both events and compile?

**Comment by WeeTomatoBall** [comment]
Yes, both events are binded and it has been compiled. It crashes when any event or function containing a delay is executed.

**Comment by WeeTomatoBall** [comment]
Can you replicate this? Steps are to use the sign in with email and password node, and out of the binded events use a delay of some sort. I'm not sure if this is only happening to me, btw my version is 5.0

**Comment by IamKingWaiMark** [comment]
From your 2nd image, 

The SignInFailed event is wrong at the bottom. Are you referring to that or the one that is connected?

Also used the Retriggerable Delay node and it still works fine on 5.0.

![image](https://user-images.githubusercontent.com/42749516/197393632-3f7206cc-e7eb-45dc-b860-a7598760c7d9.png)

**Comment by IamKingWaiMark** [comment]
Also check this post to see how to add the events:

https://codeible.com/view/videotutorial/MghD5KMFo7hLKvsHTug7;title=Auth%20-%20Sign%20In

**Comment by WeeTomatoBall** [comment]
Yes, I added the events correcty, and still, it crashes whenever there was a delay. Setting my nodes to look exactly like yours in the screenshot, it still crashes.

**Comment by IamKingWaiMark** [comment]
The Sign In With Email and Password node should be fine since you said it works without using delay.

Using a delay in the callback does not affect the node, I think you should:

1) Check the nodes after the delay

or 

2) Repair the engine files by verifying the files or reinstall/update

![image](https://user-images.githubusercontent.com/42749516/197403732-2a6be0ab-b1c8-4558-b2b1-e2c811175e9c.png)

**Comment by WeeTomatoBall** [comment]
1. Even with nothing after the delay, it crashes, the delay alone causes the crash.
2. Verifying and reinstalling has not had an effect

But I checked the logs and I found these errors right before the engine crashes (without a crash message)
LogJson: Warning: Field firebase_url was not found.
LogJson: Error: Json Value of type 'Null' used as a 'String'.

**Comment by IamKingWaiMark** [comment]
Are you using Windows or Mac?

If you are using Windows, you need to download the Google-Services.json file from the Firebase Console and add it to your root directory for the project.

Then you need to go to the Project Settings > Android (under Platforms) > Click on the Configure Now button

![image](https://user-images.githubusercontent.com/42749516/197407971-0bbbb2a8-d9be-4030-947b-62f542d24e88.png)


If you are using the Mac, you need to download the GoogleServices-info.plist file and put that file in the root folder.

**Comment by IamKingWaiMark** [comment]
Also make sure you enable Firestore or Realtime Database to generate a full Google Services file.

**Comment by WeeTomatoBall** [comment]
I've enabled Realtime Database, I've added the file, I'm using Windows, I've configured the settings. I'm not quite sure what else could be going wrong.

**Comment by WeeTomatoBall** [comment]
Is the package name important? Its just package.name right now.

**Comment by IamKingWaiMark** [comment]
Nope, the package name does not matter.

Did you enable Realtime Time Database just now? You will need to download a new Google-Services.json file.

Here is a sample google-services.json file that you can try:

https://drive.google.com/file/d/1muOnoIfVP7-eXfu64igrR0Tjy2yQ04Hk/view?usp=sharing

I made a video on how to setup the plugin:

https://www.youtube.com/watch?v=CH0p2kNH99s

**Comment by WeeTomatoBall** [comment]
Yes, I had replaced the json file, and double checking your video, I have done the setup correctly. Comparing the json you attached to my json file, it appears that the format is correct, though my ID has no numbers (racing---pod-labs) does the ID matter?

**Comment by WeeTomatoBall** [comment]
However, I just noticed that completing the same test in my level blueprint, everything works fine, the delay does not crash the editor.
![image](https://user-images.githubusercontent.com/82912271/197410057-53225789-cc27-4656-b427-9a32e2e4e3e0.png)
For some reason, it is only this same code in the widget that causes the crash. Does this happen in your widgets as well?

**Comment by IamKingWaiMark** [comment]
Nope, it works for me. 

![Sample](https://user-images.githubusercontent.com/42749516/197410328-94cab7c6-6f94-4cda-bd85-a50a7b1ae9fa.gif)

**Comment by WeeTomatoBall** [comment]
No, that is your level blueprint, can you do the same thing in a widget blueprint? I am trying to use the Plugin to create a leaderboard in my main menu, on the main menu widget, I simply add the widget in the level bp.

**Comment by IamKingWaiMark** [comment]
Oh, ok I know what you mean now.

You cannot call the plugin functions inside Widget Blueprints. 

The way to handle that is to create a function inside the Widget Blueprint and then call it to  change or updates the values inside.

![image](https://user-images.githubusercontent.com/42749516/197411398-d237cd72-2338-49f9-ad99-eb474e00d5a0.png)

**Comment by WeeTomatoBall** [comment]
Ah ok thank you.

**Comment by WeeTomatoBall** [comment]
Actually this didnt solve it. I made an actor to handle the firebase events, which I spawn on beginplay. When the sign in button is pressed, the event in the actor is called, which calls the event in the widget on fail. The delay still crashes the editor.
![image](https://user-images.githubusercontent.com/82912271/197413537-0828bdfd-c8eb-4827-b053-567ca3d49bf4.png)
![image](https://user-images.githubusercontent.com/82912271/197413607-788208bb-7bee-4c7c-b01c-dedfc7be2f60.png)

**Comment by WeeTomatoBall** [comment]
Well, actually if I put the delay in the actor rather than the widget it works. Thats odd.

**Comment by IamKingWaiMark** [comment]
Pretty interesting.

Could be something weird on how Unreal Handles Async functions and delays in widgets.
