### ISSUE TITLE
Plugin works in Editor Window and Mobile Preview but Crashes on mobile phone

### ISSUE THREAD

**Issue by bazkreyolcodes** [IamKingWaiMark/FBP#13]
The plugin works in the Editor Window and Mobile Preview , The json file was modified to include the 

        "oauth_client": [
                {
                    "client_id": "1",
                    "client_type": 3
                }
            ]
Yet whenever I press the login key or sign up key to add or read data in firestore the app crashes automatically on mobile testing. I have no other Firebase plugins enabled. This is on androids.

**Comment by nkarki** [comment]
Did you find a fix for this issue? I can fetch data from firestore when running in the editor but on mobile just building with the plugin will crash the app when running. I'm using UE 5.3
