### ISSUE TITLE
Associate data with a user

### ISSUE THREAD

**Issue by WeeTomatoBall** [IamKingWaiMark/FBP#2]
Not an issue, just a question.

So ive used the Plugin to sign in or sign up, and when you sign up, you create a username, which is stored on the firebase realtime database. Only issue is, I have no clue how to access this. The idea is that when you sign in your username would appear, but I don't know how to pull the username from the database associated with the user. How would you recommend I handle this?

**Comment by IamKingWaiMark** [comment]
You can see any of these nodes from the plugin:

![image](https://user-images.githubusercontent.com/42749516/197428237-769ca6d7-a747-45cc-9462-9208b0b6c4f8.png)

The Get Data node retrieves the data every time it is called

Listen to Value retrieves the data at the time it is called and it will be called again when there is a change to the value

Listen to Child does the same as Listen to Value but it listens for changes to everything.

The Data Path parameter represents the path to the data.

For example, if my data look like this:

![image](https://user-images.githubusercontent.com/42749516/197428475-82bf8935-3b6d-41dd-a924-361b341719d6.png)

This is how I would get the value of name from the data Bob:

![image](https://user-images.githubusercontent.com/42749516/197428595-3ec02c20-a2fd-46d0-ad3d-97db801afde7.png)
