### ISSUE TITLE
Engine Crash on Event Called

### ISSUE THREAD

**Issue by jdiab1207** [IamKingWaiMark/FBP#4]
I asked this question on the marketplace but thought it might be easier to talk about it here. 

On the event begin play I ran "Connect to firebase" and it came out true so everything is good there then I have an event in firebase for a button push then I put in all the right information like the event name, parameter and value, but when I run the game and click on the button the engine crashes. This is happening on both Mac iOS and I tried it on Windows and it does the same thing. In the crash log it says it's because or firebase so I know it's not because of some other code. The code is in a widget and I wasn't sure if that's what was causing the problem so I moved it to an event in the third person character and ran that event in the widget but it still crashes. Yes everything is up to date. Do you know what's happening?

**Comment by jdiab1207** [comment]
![image](https://user-images.githubusercontent.com/69018570/221088609-17655e5a-4e7d-4a49-b3a2-f12768a24ea1.png)
This?

**Comment by IamKingWaiMark** [comment]
Oh no, the folder of the project where you have the google-services of googleservice-info file

**Comment by jdiab1207** [comment]
Oh sorry, here it is.

![image](https://user-images.githubusercontent.com/69018570/221189001-a5612944-a683-4d85-9d08-5f9745ed9196.png)

**Comment by IamKingWaiMark** [comment]
Thanks. Ok should be good there.

Can you show me where you are using the plugin nodes?

**Comment by jdiab1207** [comment]
I use the connect to firebase in my level blueprint and it comes out as true. There's not much to see but one connect node.

**Comment by IamKingWaiMark** [comment]
Can you see what error you get?

**Comment by jdiab1207** [comment]
<img width="1075" alt="Screenshot 2023-02-24 at 9 28 44 AM" src="https://user-images.githubusercontent.com/69018570/221217950-4fd60c2a-3bdb-4fe3-8587-3ce03db3ebdc.png">
<img width="1075" alt="Screenshot 2023-02-24 at 9 29 00 AM" src="https://user-images.githubusercontent.com/69018570/221217960-e066d641-692b-42de-a73c-c843bc39da88.png">

**Comment by IamKingWaiMark** [comment]
Seems like you are missing files and not plugin related.

I think you can try to:

1) Make a copy of your project as back up.
2) Delete the Binaries, Build, Intermeidate, and Saved folder from your project
3) Open the Unreal Engine Project again and it should as you to rebuild
4) Select Yes/Ok to rebuild

**Comment by jdiab1207** [comment]
I rebuild the whole project in Visual studios multiple times and it still crashed the engine when I press the button. (The connection is always coming out true)

**Comment by IamKingWaiMark** [comment]
Do not rebuild from Visual Studio.

Delete those folders and open the project.

**Comment by IamKingWaiMark** [comment]
Also did you install these 
![image](https://user-images.githubusercontent.com/42749516/221256098-1820f6bf-33e1-4d6b-9991-ad1e9fe3ec84.png)

**Comment by IamKingWaiMark** [comment]
Use the Epic Games launcher to open the project

**Comment by jdiab1207** [comment]
Yeah, everything is installed properly. I've never had this happen before. Is there something wrong with that node? It's making my engine crash on both my windows computer and my mac book. Can you check if it actually works for you and logs the event?

**Comment by IamKingWaiMark** [comment]
I will see if I can reproduce the issue and update the code if needed. 

Will probably take 1-2 weeks for Epic Games to put the changes up.

**Comment by jdiab1207** [comment]
I don't know if that matters but I didn't create an email login because I won't require my users to do that. Is that important or not.

**Comment by jdiab1207** [comment]
Also if the information like the Event name is invalid, will it just skip it or crash?

**Comment by IamKingWaiMark** [comment]
Nope, do not need to be logged in for Analytics.

Name should be fine, if it works, it will log, if not, it will skip

**Comment by jdiab1207** [comment]
Alright then yeah somethings not working right. Thank you for trying to recreate my problem because it makes no sense to me why it would just crash the entire engine when I click on a button to log an event. Let me know if you find anything because I'm trying to run ads for my game but I need more analytics and this is the best way to do it.

**Comment by IamKingWaiMark** [comment]
Sure np.

Thanks.

**Comment by jdiab1207** [comment]
what does the Add string Parameter node do? Maybe I'm doing this wrong. What are the steps from start to finish to log an event in unreal (I already did the things in firebase correctly)

**Comment by jdiab1207** [comment]
At the event begin play in the level blueprint I put "Set Analytics Collection Enabled" to true and when I ran the game it crashed immediately. I thought that node was needed but apparently not

**Comment by IamKingWaiMark** [comment]
Ok.

I tried to reproduce the issue, I could not. But I added some code to the analytics nodes to ignore all the processes while using the editor. Let's see if that helps.

Did you try launching on a device?

**Comment by IamKingWaiMark** [comment]
The update will be live in 1 - 2 weeks

**Comment by jdiab1207** [comment]
Yeah, but if it crashes in the editor it'll just crash on mobile. You should make a video on how to fully set it up for analytics because I might be missing a step.

**Comment by IamKingWaiMark** [comment]
Sure, 

Have you launched to Android/iOS?

**Comment by jdiab1207** [comment]
![image](https://user-images.githubusercontent.com/69018570/224341197-18e963d4-ed94-472e-a339-11efda99d3b5.png)
![image](https://user-images.githubusercontent.com/69018570/224341364-4bf1c639-9c36-4024-a8b0-ef241b51417d.png)

here are my sdk configurations and my APK Packaging settings

**Comment by jdiab1207** [comment]
I'd like my money back, please. This product is not good and has only brought me problems. I will purchase from somewhere else and not use this.

**Comment by IamKingWaiMark** [comment]
Sad to hear.

Unfortunately, there is no option to refund in the Marketplace.

**Comment by jdiab1207** [comment]
In the question section, there are so many people telling you that it crashes the app or gives you errors. Have you even managed to package the game on mobile successfully?

**Comment by IamKingWaiMark** [comment]
Hello, those were all resolved and it was not due to the plugin.

And yes, it was successfully packaged on all platforms and is verified by Unreal Engine or else it cannot be published on the market,

**Comment by jdiab1207** [comment]
what ndk and jdk are you using with unreal 5.1 that's not making it crash? I created a blank project. Brought in your plugin and the .json file. Connected to firebase and it came out true and created a button that called a custom string event and when I click it, it still crashes. You claim this button works for you but I don't belive you because it should be so simple but it's not.

**Comment by IamKingWaiMark** [comment]
Hello,

No, We do not claim it works for just us. We claim that it works for anyone. 

You do not need to believe or we do not need you to believe if it works, it is a fact or else it cannot be published on the Unreal Engine Marketplace. 

You can however, attempt to publish something on the Marketplace that cannot run, build, and/or packaged and see if they will even allow it.

There is a rigorous process the Unreal Engine team does that verifies the plugin.

**Comment by jdiab1207** [comment]
You haven't answered my first question. What ndk and jdk are you using with unreal 5.1 that's not making it crash?

**Comment by IamKingWaiMark** [comment]
Hello,

We are not obligated to answer any of your questions as you said you do not believe in us nor that is a question re: the plugin functions.

You can research what you need to package an Android application on 5.1 yourself.

**Comment by jdiab1207** [comment]
Like I said, I'm able to package the game on my phone. As soon as I add your plugin. It no longer packages. This means your plugin does NOT work with ue5 and ue5.1. I have submitted a report to the unreal marketplace and they have already escalated the support case to their senior support agents.

**Comment by IamKingWaiMark** [comment]
Ok,
